name: test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.21', '1.22']
    name: Go ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          go-version: ${{ matrix.version }}
