name: test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.20', '1.21']
    name: Go ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: ./.github/actions/test
        with:
          go-version: ${{ matrix.version }}
